export type Caracteristica =
  | "Sin Fragancia"
  | "Sin Alcohol"
  | "Vegano"
  | "Sin Parabenos"
  | "Apto Sensibles"
  | "Mineral"
  | "Probado Dermat.";

// Characteristics indexed by product id
export const productCaracteristicas: Record<number, Caracteristica[]> = {
  1:  ["Apto Sensibles", "Vegano", "Sin Parabenos"],
  2:  ["Apto Sensibles", "Sin Parabenos"],
  3:  ["Sin Fragancia", "Sin Parabenos"],
  4:  ["Vegano", "Sin Parabenos"],
  5:  ["Sin Fragancia", "Sin Parabenos"],
  6:  ["Sin Fragancia", "Apto Sensibles", "Sin Parabenos"],
  7:  ["Apto Sensibles", "Sin Parabenos"],
  8:  ["Vegano", "Sin Parabenos"],
  9:  ["Probado Dermat.", "Sin Parabenos"],
  10: ["Probado Dermat.", "Apto Sensibles", "Sin Parabenos"],
  11: ["Probado Dermat.", "Sin Parabenos"],
  12: ["Probado Dermat.", "Sin Parabenos"],
  13: ["Probado Dermat.", "Sin Parabenos"],
  14: ["Sin Parabenos"],
  15: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  16: ["Probado Dermat.", "Sin Parabenos"],
  17: ["Sin Fragancia", "Sin Parabenos"],
  18: ["Sin Parabenos"],
  19: ["Vegano", "Sin Parabenos"],
  20: ["Probado Dermat.", "Sin Parabenos"],
  21: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  22: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  23: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  24: ["Sin Fragancia", "Vegano", "Sin Parabenos", "Apto Sensibles"],
  25: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  26: ["Sin Fragancia", "Vegano"],
  27: ["Vegano", "Sin Parabenos"],
  28: ["Sin Parabenos"],
  29: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  30: ["Sin Fragancia", "Vegano", "Sin Parabenos", "Apto Sensibles"],
  31: ["Sin Parabenos"],
  32: ["Sin Fragancia", "Vegano", "Sin Parabenos", "Apto Sensibles"],
  33: ["Sin Fragancia", "Sin Parabenos"],
  34: ["Sin Fragancia", "Sin Parabenos"],
  35: ["Apto Sensibles", "Sin Parabenos"],
  36: ["Apto Sensibles", "Sin Parabenos"],
  37: ["Sin Parabenos"],
  38: ["Sin Parabenos"],
  39: ["Sin Fragancia", "Vegano", "Sin Parabenos", "Apto Sensibles"],
  40: ["Sin Fragancia", "Vegano", "Sin Parabenos", "Apto Sensibles"],
  41: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  42: ["Sin Fragancia", "Sin Parabenos"],
  43: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  44: ["Sin Parabenos"],
  45: ["Mineral", "Sin Fragancia", "Apto Sensibles"],
  46: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  47: ["Apto Sensibles", "Sin Parabenos"],
  48: ["Sin Fragancia", "Sin Parabenos"],
  49: ["Sin Parabenos"],
  50: ["Sin Fragancia", "Sin Parabenos"],
  51: ["Sin Fragancia", "Apto Sensibles", "Sin Parabenos"],
  52: ["Sin Parabenos"],
  53: ["Sin Parabenos"],
  54: ["Sin Fragancia", "Apto Sensibles", "Sin Parabenos"],
  55: ["Sin Fragancia", "Vegano", "Sin Parabenos", "Apto Sensibles"],
  56: ["Sin Fragancia", "Sin Parabenos"],
  57: ["Sin Fragancia", "Sin Parabenos"],
  58: ["Apto Sensibles", "Sin Parabenos"],
  59: ["Mineral", "Sin Fragancia", "Apto Sensibles"],
  60: ["Sin Parabenos"],
  61: ["Sin Fragancia", "Vegano", "Sin Parabenos"],
  62: ["Sin Parabenos"],
  63: ["Sin Parabenos"],
  64: ["Sin Fragancia", "Sin Parabenos"],
  65: ["Sin Fragancia", "Sin Parabenos"],
  66: ["Sin Fragancia", "Sin Parabenos"],
  67: ["Apto Sensibles", "Sin Parabenos"],
  68: ["Sin Parabenos"],
  69: ["Sin Parabenos"],
};
