export type ProductCategory =
  | "Todos"
  | "Limpiadores"
  | "Tónicos"
  | "Sueros"
  | "Hidratantes"
  | "Mascarillas & Pads"
  | "Protección Solar"
  | "Sets & Kits"
  | "Cabello";

export const tipoPielOptions = [
  "Todas",
  "Sensible",
  "Mixta",
  "Grasa",
  "Seca",
  "Madura",
  "Normal",
] as const;
export type TipoPielFilter = (typeof tipoPielOptions)[number];

export const concernOptions = [
  "Todos",
  "Calmante",
  "Manchas",
  "Antiage",
  "Hidratación",
  "Limpieza",
  "Acné",
  "Protector solar",
  "Cabello",
] as const;
export type ConcernFilter = (typeof concernOptions)[number];

export interface Product {
  id: number;
  name: string;
  brand: string;
  store: "BS" | "YEPPO";
  category: Exclude<ProductCategory, "Todos">;
  description: string;
  images: string[];
  tag?: string;
  featured?: boolean;
  price?: number;
  size?: string;
  tipoProducto?: string;
  beneficio?: string;
  tipoPiel?: string;
  concern?: string;
}

// Helper: encode path segments with special characters for use in <img src>
export function imgSrc(path: string): string {
  const base = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
  return (
    base +
    "/" +
    path
      .split("/")
      .map((seg) => encodeURIComponent(seg))
      .join("/")
  );
}

const BS = "Foto Productos/BS";
const YP = "Foto Productos/YEPPO";

export const products: Product[] = [
  // ── ANUA ─────────────────────────────────────────────────
  {
    id: 1,
    name: "Heartleaf Quercetinol Cleansing Foam 150ml",
    brand: "ANUA",
    store: "BS",
    category: "Limpiadores",
    description:
      "Espuma limpiadora con Heartleaf al 77% y quercetinol. Elimina impurezas sin dañar la barrera cutánea, ideal para pieles sensibles y propensas al acné.",
    images: [
      `${BS}/ANUA Heartleaf Quercetinol Cleansing Foam – Jabon de Limpieza Facial 150ml/poredeep1.webp`,
      `${BS}/ANUA Heartleaf Quercetinol Cleansing Foam – Jabon de Limpieza Facial 150ml/poredeep2.webp`,
      `${BS}/ANUA Heartleaf Quercetinol Cleansing Foam – Jabon de Limpieza Facial 150ml/poredeep3.webp`,
      `${BS}/ANUA Heartleaf Quercetinol Cleansing Foam – Jabon de Limpieza Facial 150ml/poredeep4.webp`,
      `${BS}/ANUA Heartleaf Quercetinol Cleansing Foam – Jabon de Limpieza Facial 150ml/poredeep5.webp`,
    ],
    price: 18900,
    size: "150 ml",
    tipoProducto: "Jabón",
    beneficio: "Calma y limpia",
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 2,
    name: "Heartleaf Trial Kit – 4 pzs",
    brand: "ANUA",
    store: "BS",
    category: "Sets & Kits",
    description:
      "Descubre la línea Heartleaf en miniatura. Kit de 4 productos para calmar, limpiar y fortalecer la piel sensible.",
    images: [
      `${BS}/ANUA Heartleaf Trial Kit – 4 pzs/122_png_f2fe4d37-3f64-4ba5-9f40-cd6e108fba20-1-1024x1024.webp`,
      `${BS}/ANUA Heartleaf Trial Kit – 4 pzs/anua-toner-heartleaf-soothing-trial-kit-4-items-42014963007766.webp`,
      `${BS}/ANUA Heartleaf Trial Kit – 4 pzs/heartleaf80_5.jpg`,
    ],
    price: 29990,
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 3,
    name: "PDRN Hyaluronic Acid 100 Cream 60ml",
    brand: "ANUA",
    store: "BS",
    category: "Hidratantes",
    description:
      "Crema ultra-hidratante con PDRN (ADN de salmón) e ácido hialurónico puro. Rellena y plumpa la piel desde adentro.",
    images: [
      `${BS}/ANUA PDRN Hyaluronic Acid 100 Cream – 60 ml/anua-1024x1024.jpg`,
      `${BS}/ANUA PDRN Hyaluronic Acid 100 Cream – 60 ml/anua-2-1024x1024.jpg`,
      `${BS}/ANUA PDRN Hyaluronic Acid 100 Cream – 60 ml/anau-3-1024x1024.jpg`,
      `${BS}/ANUA PDRN Hyaluronic Acid 100 Cream – 60 ml/anua-pdrn-1024x1024.jpg`,
      `${BS}/ANUA PDRN Hyaluronic Acid 100 Cream – 60 ml/anua-pdrn-2-1024x1024.jpg`,
      `${BS}/ANUA PDRN Hyaluronic Acid 100 Cream – 60 ml/anua-pdrn-4-1024x1024.jpg`,
      `${BS}/ANUA PDRN Hyaluronic Acid 100 Cream – 60 ml/anua-pdrn-5-1024x1024.jpg`,
    ],
    price: 34900,
    size: "60 ml",
    tipoProducto: "Crema",
    beneficio: "Regeneración antiage",
    tipoPiel: "Madura",
    concern: "Antiage",
  },
  {
    id: 4,
    name: "Peach 70% Niacinamide Serum 30ml",
    brand: "ANUA",
    store: "BS",
    category: "Sueros",
    tag: "Bestseller",
    featured: true,
    description:
      "Sérum iluminador con extracto de durazno al 70% y niacinamida. Unifica el tono, reduce manchas y aporta esa luminosidad jugosa.",
    images: [
      `${BS}/ANUA Peach 70_ Niacinamide Serum Iluminador 30ml/41UsAM1r9bL._SL1000_.jpg`,
      `${BS}/ANUA Peach 70_ Niacinamide Serum Iluminador 30ml/61uzV1DuThL._SL1080_-1024x1024.jpg`,
      `${BS}/ANUA Peach 70_ Niacinamide Serum Iluminador 30ml/71DrfvY7PL._SL1080_-1024x1024.jpg`,
    ],
    price: 29000,
    size: "30 ml",
    tipoProducto: "Serum",
    beneficio: "Ilumina manchas",
    tipoPiel: "Mixta",
    concern: "Manchas",
  },
  {
    id: 5,
    name: "PDRN Hyaluronic Acid Capsule 100 Serum 30ml",
    brand: "ANUA",
    store: "YEPPO",
    category: "Sueros",
    description:
      "Sérum con PDRN encapsulado e ácido hialurónico puro. Rellena poros, borra arrugas finas y da un efecto plump visible desde la primera semana.",
    images: [
      `${YP}/[ANUA] PDRN Hyaluronic Acid Capsule 100 Serum 30ml/Anua-0191-1536x1536.jpg`,
    ],
    price: 34900,
    size: "30 ml",
    tipoProducto: "Serum",
    beneficio: "Hidratación y firmeza",
    tipoPiel: "Mixta, seca",
    concern: "Hidratación",
  },
  {
    id: 6,
    name: "Azelaic Acid 10 Hyaluron Redness Serum 30ml",
    brand: "ANUA",
    store: "YEPPO",
    category: "Sueros",
    description:
      "Sérum con ácido azelaico al 10% e hialurónico. Calma la rojez, unifica el tono y combate el acné con una fórmula suave sin irritación.",
    images: [
      `${YP}/[Anua] Azelaic Acid 10 Hyaluron Redness Soothing Serum 30ml/Anua-0201-1536x1536.jpg`,
    ],
    price: 32900,
    size: "30 ml",
    tipoProducto: "Serum",
    beneficio: "Reduce rojeces y combate manchas",
    tipoPiel: "Sensible, mixta y grasa",
    concern: "Calmante",
  },
  {
    id: 7,
    name: "Heartleaf Pore Control Cleansing Oil 200ml",
    brand: "ANUA",
    store: "YEPPO",
    category: "Limpiadores",
    tag: "Nuevo",
    description:
      "Aceite limpiador con Heartleaf al 77%. Control de poros desde el primer paso, elimina impurezas y maquillaje sin irritar.",
    images: [
      `${YP}/[Anua] Heartleaf Pore Control Cleansing Oil Mild 200ml/ANUA-013-1-1.jpg`,
      `${YP}/[Anua] Heartleaf Pore Control Cleansing Oil Mild 200ml/ANUA-013-2-640x640.jpg`,
      `${YP}/[Anua] Heartleaf Pore Control Cleansing Oil Mild 200ml/ANUA-013-3-1536x1536.jpg`,
      `${YP}/[Anua] Heartleaf Pore Control Cleansing Oil Mild 200ml/ANUA-013-4-640x640.jpg`,
    ],
    price: 30900,
    size: "200 ml",
    tipoProducto: "Limpiador oil",
    beneficio: "Limpieza profunda",
    tipoPiel: "Mixta",
    concern: "Limpieza",
  },
  {
    id: 8,
    name: "Niacinamide 10 TXA 4 Serum",
    brand: "ANUA",
    store: "YEPPO",
    category: "Sueros",
    description:
      "Sérum con niacinamida al 10% y ácido tranexámico al 4%. Doble acción: controla manchas y regula el sebo en una sola fórmula de alto impacto.",
    images: [
      `${YP}/[Anua] Niacinamide 10 TXA 4 Serum/Imagenprimaria_1fdcfaa9-e468-40da-bc0b-3dd1f15368a6.jpg`,
      `${YP}/[Anua] Niacinamide 10 TXA 4 Serum/PlantillaFotosWeb_1_2_be344cc4-cfa0-474f-bf04-637171fc313d.jpg`,
      `${YP}/[Anua] Niacinamide 10 TXA 4 Serum/PlantillaFotosWeb_1_4_a5785506-4939-4858-9e8f-042c76654b9d.jpg`,
      `${YP}/[Anua] Niacinamide 10 TXA 4 Serum/PlantillaFotosWeb_1_6_2f01ffb4-9604-4529-a39c-0d1aa77b0327-640x640.jpg`,
    ],
    price: 32900,
    size: "30 ml",
    tipoProducto: "Serum",
    beneficio: "Manchas",
    tipoPiel: "Todo tipo",
    concern: "Manchas",
  },

  // ── DR. ALTHEA ───────────────────────────────────────────
  {
    id: 9,
    name: "Vitamin C Boosting Serum 30ml",
    brand: "Dr. Althea",
    store: "BS",
    category: "Sueros",
    description:
      "Sérum de vitamina C estabilizada. Ilumina, protege de radicales libres y difumina manchas con una textura ligera que absorbe al instante.",
    images: [
      `${BS}/DR. ALTHEA Vitamin C Boosting Serum – 30ml/vita-7.webp`,
    ],
    price: 24900,
    size: "30 ml",
    tipoProducto: "Serum",
    beneficio: "Ilumina piel",
    tipoPiel: "Todo tipo",
    concern: "Manchas",
  },
  {
    id: 10,
    name: "147 Barrier Cream 50ml",
    brand: "Dr. Althea",
    store: "YEPPO",
    category: "Hidratantes",
    description:
      "Crema barrera con 147 ingredientes nutritivos. Restaura y fortalece la capa protectora, ideal para pieles secas, sensibles o comprometidas.",
    images: [
      `${YP}/Dr. Althea147 Barrier Cream 50ml/Althea-0021_630x630.webp`,
      `${YP}/Dr. Althea147 Barrier Cream 50ml/Althea-002-2_630x630.webp`,
      `${YP}/Dr. Althea147 Barrier Cream 50ml/Althea-002-3_630x630.webp`,
      `${YP}/Dr. Althea147 Barrier Cream 50ml/Althea-002-4_630x630.webp`,
      `${YP}/Dr. Althea147 Barrier Cream 50ml/Althea-002-5_630x630.webp`,
    ],
    price: 33000,
    size: "50 ml",
    tipoProducto: "Crema",
    beneficio: "Repara piel",
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 11,
    name: "345 Relief Cream 50ml",
    brand: "Dr. Althea",
    store: "YEPPO",
    category: "Hidratantes",
    description:
      "Crema calmante con fórmula 3-4-5: tres ceramidas, cuatro extractos botánicos y cinco activos reparadores para pieles en distress.",
    images: [
      `${YP}/[Dr.Althea] 345 Relief Cream (50ml)/Althea-001-1-1536x1536.jpg`,
      `${YP}/[Dr.Althea] 345 Relief Cream (50ml)/Althea-001-2-1536x1536.jpg`,
      `${YP}/[Dr.Althea] 345 Relief Cream (50ml)/Althea-001-3-1536x1536.jpg`,
      `${YP}/[Dr.Althea] 345 Relief Cream (50ml)/Althea-001-4-640x640.jpg`,
      `${YP}/[Dr.Althea] 345 Relief Cream (50ml)/Althea-001-5-640x640.jpg`,
    ],
    price: 33000,
    size: "50 ml",
    tipoProducto: "Crema",
    beneficio: "Control acné",
    tipoPiel: "Grasa",
    concern: "Acné",
  },
  {
    id: 12,
    name: "Pore Refresh Grinding Cleansing Balm 50g",
    brand: "Dr. Althea",
    store: "YEPPO",
    category: "Limpiadores",
    description:
      "Bálsamo limpiador con microesferas de arcilla que refinan los poros. Transición de sólido a aceite al contacto, elimina sebo e impurezas en profundidad.",
    images: [
      `${YP}/[Dr.Althea] Pore Refresh Grinding Cleansing Balm 50g/Althea-0082.jpg`,
      `${YP}/[Dr.Althea] Pore Refresh Grinding Cleansing Balm 50g/Althea-0083.jpg`,
      `${YP}/[Dr.Althea] Pore Refresh Grinding Cleansing Balm 50g/Althea-0084-1536x1536.jpg`,
      `${YP}/[Dr.Althea] Pore Refresh Grinding Cleansing Balm 50g/Althea-0085-1536x1536.jpg`,
    ],
    price: 21900,
    size: "50 g",
    tipoProducto: "Limpieza",
    beneficio: "Hidrata, elimina sebo, pieles sensibles",
    tipoPiel: "Todo tipo",
    concern: "Limpieza",
  },
  {
    id: 13,
    name: "Pure Grinding Cleansing Balm 50g",
    brand: "Dr. Althea",
    store: "YEPPO",
    category: "Limpiadores",
    description:
      "Bálsamo limpiador puro que se convierte en aceite al aplicar. Disuelve hasta el maquillaje waterproof dejando la piel suave y nutrida.",
    images: [
      `${YP}/[Dr.Althea] Pure Grinding Cleansing Balm 50g/Althea-0071.jpg`,
      `${YP}/[Dr.Althea] Pure Grinding Cleansing Balm 50g/Althea-0072-1536x1536.jpg`,
      `${YP}/[Dr.Althea] Pure Grinding Cleansing Balm 50g/Althea-0073-1536x1536.jpg`,
      `${YP}/[Dr.Althea] Pure Grinding Cleansing Balm 50g/Althea-0074-640x640.jpg`,
      `${YP}/[Dr.Althea] Pure Grinding Cleansing Balm 50g/Althea-0075-640x640.jpg`,
    ],
    price: 21900,
    size: "50 g",
    tipoProducto: "Limpieza",
    beneficio: "Rojeces, pieles sensibles",
    tipoPiel: "Todo tipo",
    concern: "Limpieza",
  },

  // ── ELIZAVECCA ───────────────────────────────────────────
  {
    id: 14,
    name: "CER-100 Collagen Ceramide Coating Hair Treatment",
    brand: "Elizavecca",
    store: "YEPPO",
    category: "Cabello",
    description:
      "Tratamiento capilar con colágeno y ceramidas que recubre el cabello dañado. Devuelve brillo, suavidad y resistencia desde la primera aplicación.",
    images: [
      `${YP}/[Elizavecca] CER-100 Collagen Ceramide Coating Hair Protein Treatment/COLLAGEN-COATING-HAIR-PROTEIN-TREATMENT-CER-100-1.jpg`,
      `${YP}/[Elizavecca] CER-100 Collagen Ceramide Coating Hair Protein Treatment/COLLAGEN-COATING-HAIR-PROTEIN-TREATMENT-CER-100-5-640x640.jpg`,
      `${YP}/[Elizavecca] CER-100 Collagen Ceramide Coating Hair Protein Treatment/COLLAGEN-COATING-HAIR-PROTEIN-TREATMENT-CER-100-6-640x640.jpg`,
      `${YP}/[Elizavecca] CER-100 Collagen Ceramide Coating Hair Protein Treatment/COLLAGEN-COATING-HAIR-PROTEIN-TREATMENT-CER-100-7.jpg`,
    ],
    price: 12500,
    tipoProducto: "Cabello",
    beneficio: "Reparación capilar",
    concern: "Cabello",
  },

  // ── IUNIK ────────────────────────────────────────────────
  {
    id: 15,
    name: "Centella Mini Set",
    brand: "IUNIK",
    store: "YEPPO",
    category: "Sets & Kits",
    description:
      "Mini set con los esenciales de Centella de iUNIK: tónico y sérum en talla perfecta para probar o llevar de viaje.",
    images: [
      `${YP}/[IUNIK] Centella Mini Set/iUnik-Centella-Mini-Set-1.jpg`,
      `${YP}/[IUNIK] Centella Mini Set/iUnik-Centella-Mini-Set-2.jpg`,
    ],
    price: 19000,
    tipoPiel: "Sensible",
    concern: "Calmante",
  },

  // ── MEDICUBE ─────────────────────────────────────────────
  {
    id: 16,
    name: "PDRN Pink Collagen Gel Mask",
    brand: "MEDICUBE",
    store: "BS",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla de gel con PDRN y colágeno rosa. Regenera la piel mientras duermes, dejándola rellena, firme y con efecto glow al despertar.",
    images: [
      `${BS}/MEDICUBE PDRN Pink Collagen Gel Mask – Mascarilla Antiage/pinkmask2.webp`,
      `${BS}/MEDICUBE PDRN Pink Collagen Gel Mask – Mascarilla Antiage/pinkmask3.webp`,
      `${BS}/MEDICUBE PDRN Pink Collagen Gel Mask – Mascarilla Antiage/pinkmask4.webp`,
      `${BS}/MEDICUBE PDRN Pink Collagen Gel Mask – Mascarilla Antiage/pinkmask5.webp`,
      `${BS}/MEDICUBE PDRN Pink Collagen Gel Mask – Mascarilla Antiage/pinkmask6.webp`,
      `${BS}/MEDICUBE PDRN Pink Collagen Gel Mask – Mascarilla Antiage/pinkmask8.webp`,
    ],
    price: 6700,
    size: "1 u",
    tipoProducto: "Máscara",
    beneficio: "Antiarrugas",
    tipoPiel: "Madura",
    concern: "Antiage",
  },
  {
    id: 17,
    name: "Zero Pore Pad 2.0",
    brand: "MEDICUBE",
    store: "BS",
    category: "Mascarillas & Pads",
    description:
      "Almohadillas exfoliantes con BHA y AHA que refinan los poros, eliminan células muertas y controlan el sebo. Piel visiblemente más suave y limpia.",
    images: [
      `${BS}/MEDICUBE Zero Pore Pad 2.0 – Almohadillas Exfoliantes/zeropad1.webp`,
      `${BS}/MEDICUBE Zero Pore Pad 2.0 – Almohadillas Exfoliantes/zeropad2-1024x1024.webp`,
      `${BS}/MEDICUBE Zero Pore Pad 2.0 – Almohadillas Exfoliantes/zeropad3-1024x1024.webp`,
      `${BS}/MEDICUBE Zero Pore Pad 2.0 – Almohadillas Exfoliantes/zeropad4-1024x1024.webp`,
      `${BS}/MEDICUBE Zero Pore Pad 2.0 – Almohadillas Exfoliantes/zeropad6.webp`,
      `${BS}/MEDICUBE Zero Pore Pad 2.0 – Almohadillas Exfoliantes/zeropad7.webp`,
    ],
    price: 29900,
    size: "70 u",
    tipoProducto: "PAD+Tónico",
    beneficio: "Reduce poros",
    tipoPiel: "Grasa",
    concern: "Acné",
  },
  {
    id: 18,
    name: "Collagen Night Wrapping Mask",
    brand: "MEDICUBE",
    store: "YEPPO",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla nocturna de colágeno en formato wrap. Envuelve la piel de nutrición durante la noche para un efecto lifting visible al despertar.",
    images: [
      `${YP}/[Medicube] Collagen Night Wrapping Mask/MEDICUBE-001-1-1536x1536.jpg`,
      `${YP}/[Medicube] Collagen Night Wrapping Mask/MEDICUBE-001-2-640x640.jpg`,
      `${YP}/[Medicube] Collagen Night Wrapping Mask/MEDICUBE-001-3-640x640.jpg`,
      `${YP}/[Medicube] Collagen Night Wrapping Mask/MEDICUBE-001-4-1536x1536.jpg`,
      `${YP}/[Medicube] Collagen Night Wrapping Mask/MEDICUBE-001-5-1536x1536.jpg`,
    ],
    price: 34900,
    size: "75 ml",
  },
  {
    id: 19,
    name: "Deep Vita C Capsule Cream 55g",
    brand: "MEDICUBE",
    store: "YEPPO",
    category: "Hidratantes",
    description:
      "Crema con cápsulas de vitamina C que estallan al aplicar. Ilumina intensamente, difumina manchas y aporta firmeza con cada uso.",
    images: [
      `${YP}/[Medicube] Deep Vita C Capsule Cream 55g/MEDICUBE-003-1-1536x1536.jpg`,
      `${YP}/[Medicube] Deep Vita C Capsule Cream 55g/MEDICUBE-003-2-640x640.jpg`,
      `${YP}/[Medicube] Deep Vita C Capsule Cream 55g/MEDICUBE-003-3-1536x1536.jpg`,
      `${YP}/[Medicube] Deep Vita C Capsule Cream 55g/MEDICUBE-003-4-640x640.jpg`,
    ],
    price: 41900,
    size: "55 g",
    beneficio: "Reafirmar y manchas",
    tipoPiel: "Todo tipo",
    concern: "Antiage",
  },
  {
    id: 20,
    name: "PDRN Pink Collagen Capsule Cream",
    brand: "MEDICUBE",
    store: "YEPPO",
    category: "Hidratantes",
    description:
      "Crema rosa con PDRN y colágeno encapsulado. Estimula la regeneración celular y el efecto relleno que se nota desde el día uno.",
    images: [
      `${YP}/[Medicube] PDRN Pink Collagen Capsule Cream/MEDICUBE-005-1-1536x1536.jpg`,
      `${YP}/[Medicube] PDRN Pink Collagen Capsule Cream/MEDICUBE-005-2-1536x1536.jpg`,
      `${YP}/[Medicube] PDRN Pink Collagen Capsule Cream/MEDICUBE-005-3-1536x1536.jpg`,
      `${YP}/[Medicube] PDRN Pink Collagen Capsule Cream/MEDICUBE-005-4-640x640.jpg`,
    ],
    price: 36900,
    size: "55 g",
    tipoProducto: "Crema",
    beneficio: "Reafirmar y manchas",
    tipoPiel: "Todo tipo",
    concern: "Antiage",
  },

  // ── MIXSOON ──────────────────────────────────────────────
  {
    id: 21,
    name: "Bean Cleansing Oil 100ml",
    brand: "MIXSOON",
    store: "BS",
    category: "Limpiadores",
    description:
      "Aceite limpiador de soja 100ml. Disuelve maquillaje, SPF y sebo sin dejar sensación oleosa. El primer paso ideal de tu doble limpieza.",
    images: [
      `${BS}/MIXSOON Bean Cleansing Oil – 100ml/OIL2-1024x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – 100ml/OIL4-935x1536-1-623x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – 100ml/OIL5-675x1024-1.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – 100ml/OIL6-985x1536-1-657x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – 100ml/OIL7-935x1536-1-623x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – 100ml/OIL8-855x1536-1.webp`,
    ],
    price: 14990,
    size: "100 ml",
    tipoProducto: "Limpieza",
    beneficio: "Limpieza aceite",
    tipoPiel: "Todo tipo",
    concern: "Limpieza",
  },
  {
    id: 22,
    name: "Bean Cleansing Oil 195ml",
    brand: "MIXSOON",
    store: "BS",
    category: "Limpiadores",
    tag: "Tamaño Grande",
    description:
      "Versión maxi del aceite limpiador de soja. Mayor rendimiento para quienes no pueden vivir sin este indispensable del K-beauty.",
    images: [
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL1-1024x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL2-1024x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL3-845x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL4-623x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL5-675x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL6-656x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL7-623x1024.webp`,
      `${BS}/MIXSOON Bean Cleansing Oil – Aceite de limpieza 195ml/OIL8-855x1536.webp`,
    ],
    price: 24900,
    size: "195 ml",
    tipoProducto: "Limpieza",
    beneficio: "Limpieza aceite",
    tipoPiel: "Todo tipo",
    concern: "Limpieza",
  },
  {
    id: 23,
    name: "Bean Essence Sérum Exfoliante 50ml",
    brand: "MIXSOON",
    store: "BS",
    category: "Sueros",
    description:
      "Sérum-esencia con extracto de soja fermentada y AHA suave. Exfolia, nutre y deja la piel con un brillo natural y saludable.",
    images: [
      `${BS}/MIXSOON Bean Essence Serum Exfoliante nutritivo 50ml/BEANESSENCE5.webp`,
      `${BS}/MIXSOON Bean Essence Serum Exfoliante nutritivo 50ml/BEANESSENCE6.webp`,
      `${BS}/MIXSOON Bean Essence Serum Exfoliante nutritivo 50ml/beanessence1-729x1024.webp`,
      `${BS}/MIXSOON Bean Essence Serum Exfoliante nutritivo 50ml/beamessence2-809x1024.webp`,
      `${BS}/MIXSOON Bean Essence Serum Exfoliante nutritivo 50ml/beanessence3-704x1024.webp`,
      `${BS}/MIXSOON Bean Essence Serum Exfoliante nutritivo 50ml/beanessence7.webp`,
    ],
    price: 32000,
    size: "50 ml",
    tipoProducto: "Serum",
    beneficio: "Glow coreano",
    tipoPiel: "Todo tipo",
    concern: "Hidratación",
  },
  {
    id: 24,
    name: "Centella Cleansing Foam 150ml",
    brand: "MIXSOON",
    store: "BS",
    category: "Limpiadores",
    description:
      "Espuma limpiadora con Centella Asiatica para pieles propensas al acné. Purifica sin resecar, calmando la piel enrojecida.",
    images: [
      `${BS}/MIXSOON Centella Cleansing Foam Jabón Antiacné 150ml/cicafoam1.webp`,
      `${BS}/MIXSOON Centella Cleansing Foam Jabón Antiacné 150ml/cicafoam2.webp`,
      `${BS}/MIXSOON Centella Cleansing Foam Jabón Antiacné 150ml/cicafoam3.webp`,
      `${BS}/MIXSOON Centella Cleansing Foam Jabón Antiacné 150ml/cicafoam4.webp`,
      `${BS}/MIXSOON Centella Cleansing Foam Jabón Antiacné 150ml/cicafoam5.webp`,
      `${BS}/MIXSOON Centella Cleansing Foam Jabón Antiacné 150ml/cicafoam7.webp`,
    ],
    price: 17500,
    size: "150 ml",
    tipoProducto: "Jabón",
    beneficio: "Control acné",
    tipoPiel: "Grasa",
    concern: "Acné",
  },
  {
    id: 25,
    name: "Master Serum 30ml",
    brand: "MIXSOON",
    store: "BS",
    category: "Sueros",
    description:
      "Sérum concentrado multi-activo que calma, nutre y regenera. Un solo paso que reemplaza varios productos en tu rutina.",
    images: [
      `${BS}/MIXSOON Master Serum – 30ml/41w7br8nCDL._SL1500_.jpg`,
      `${BS}/MIXSOON Master Serum – 30ml/51QnVVfoh-L._SL1000_.jpg`,
      `${BS}/MIXSOON Master Serum – 30ml/51XFezdIvGL._SL1000_.jpg`,
      `${BS}/MIXSOON Master Serum – 30ml/51fsTCSa7ZL._SL1000_.jpg`,
      `${BS}/MIXSOON Master Serum – 30ml/61eHsfvEUGL._SL1000_.jpg`,
    ],
    price: 24900,
    size: "30 ml",
    tipoProducto: "Serum",
    beneficio: "Hidratación premium",
    tipoPiel: "Seca",
    concern: "Hidratación",
  },
  {
    id: 26,
    name: "House Bean Special Line Set – 4 pzs",
    brand: "MIXSOON",
    store: "BS",
    category: "Sets & Kits",
    description:
      "Set especial de la línea Bean en presentación de edición especial. Incluye 4 productos con extracto de soja fermentada.",
    images: [
      `${BS}/MIXSOON – House Bean Special Line Set – 4 piezas/L_g0222695447_000.webp`,
      `${BS}/MIXSOON – House Bean Special Line Set – 4 piezas/L_g0222695447_002.webp`,
      `${BS}/MIXSOON – House Bean Special Line Set – 4 piezas/mixsoon_House_Bean_Holiday_Edition_Set_THEKSHOP_Canada.webp`,
    ],
    price: 65000,
    beneficio: "Hidratación glow",
    tipoPiel: "Todo tipo",
    concern: "Hidratación",
  },
  {
    id: 27,
    name: "PDRN Collagen Gel Cleanser 100ml",
    brand: "MIXSOON",
    store: "BS",
    category: "Limpiadores",
    description:
      "Jabón facial en gel con PDRN y colágeno. Limpia profundamente mientras aporta firmeza e hidratación desde el primer paso de tu rutina.",
    images: [
      `${BS}/MIXSOON – PDRN Collagen Gel Cleanser – Jabón Facial 100ml/l_g0219986343_009-966de8d0acdd14e6ff17580609215000-640-0.webp`,
    ],
    price: 19900,
    size: "100 ml",
    tipoProducto: "Jabón",
    beneficio: "Hidratación profunda",
    tipoPiel: "Todo tipo",
    concern: "Limpieza",
  },
  {
    id: 28,
    name: "PDRN Collagen Hydrogel Mask – Caja 5 pzs",
    brand: "MIXSOON",
    store: "BS",
    category: "Mascarillas & Pads",
    description:
      "Set de 5 mascarillas de hidrogel con PDRN y colágeno. Intensa recuperación cutánea en 20 minutos con efecto tensor visible.",
    images: [
      `${BS}/MIXSOON – PDRN Collagen Hydrogel Mask – Caja x 5 pzs/pdrn.png`,
      `${BS}/MIXSOON – PDRN Collagen Hydrogel Mask – Caja x 5 pzs/pdrn2.png`,
    ],
    price: 24900,
    size: "5 u",
    tipoProducto: "Máscara",
  },
  {
    id: 29,
    name: "Pure Glow Essentials Set – 5 pzs",
    brand: "MIXSOON",
    store: "BS",
    category: "Sets & Kits",
    description:
      "Kit de 5 productos en mini talla: limpiador, tónico, sérum, esencia y crema. Ideal para descubrir la línea completa de MIXSOON.",
    images: [
      `${BS}/MIXSOON – Pure Glow Essentials Set – Kit Mini Tallas – 5 pzs/41pVqUpS42L._SL1000_.jpg`,
      `${BS}/MIXSOON – Pure Glow Essentials Set – Kit Mini Tallas – 5 pzs/510WNxMhVPL._SL1000_.jpg`,
      `${BS}/MIXSOON – Pure Glow Essentials Set – Kit Mini Tallas – 5 pzs/511bKHTWFiL._SL1000_.jpg`,
      `${BS}/MIXSOON – Pure Glow Essentials Set – Kit Mini Tallas – 5 pzs/51XcdLL1wfL._SL1000_.jpg`,
    ],
    price: 29900,
    beneficio: "Hidratación glow",
    tipoPiel: "Todo tipo",
    concern: "Hidratación",
  },
  {
    id: 30,
    name: "Bean Cream",
    brand: "MIXSOON",
    store: "YEPPO",
    category: "Hidratantes",
    description:
      "Crema de soja fermentada de textura aireada. Hidrata sin pesar, regula el sebo y es un favorito de K-beauty para pieles normales a mixtas.",
    images: [
      `${YP}/[Mixsoon] Bean Cream/Mixsoon-003-1_7441a78b-252d-49c4-bb58-91ca285f0c88.jpg`,
      `${YP}/[Mixsoon] Bean Cream/Mixsoon-003-2_3c0e082d-6754-4f80-8b0f-c71be9def5e8-1536x1536.jpg`,
      `${YP}/[Mixsoon] Bean Cream/Mixsoon-003-3_0f7e6d86-1cb8-4b30-8e65-24c17f43ade4-1536x1536.jpg`,
      `${YP}/[Mixsoon] Bean Cream/Mixsoon-003-5_8e1f1f39-d0ed-4295-a195-bc66793ba506-640x640.jpg`,
    ],
    price: 37980,
    size: "50 ml",
    tipoProducto: "Crema",
    beneficio: "Hidratación profunda",
    tipoPiel: "Todo tipo",
    concern: "Antiage",
  },

  // ── PURITO ───────────────────────────────────────────────
  {
    id: 31,
    name: "Mighty Bamboo Panthenol Cream 100ml",
    brand: "Purito",
    store: "YEPPO",
    category: "Hidratantes",
    description:
      "Crema rica en extracto de bambú y pantenol. Repara la piel dañada, sella la hidratación y alivia la irritación con textura suave.",
    images: [
      `${YP}/Purito Mighty Bamboo Panthenol Cream 100ml/Purito-0271-1536x1536.jpg`,
      `${YP}/Purito Mighty Bamboo Panthenol Cream 100ml/Purito-0272-1536x1536.jpg`,
      `${YP}/Purito Mighty Bamboo Panthenol Cream 100ml/Purito-0273-1536x1536.jpg`,
      `${YP}/Purito Mighty Bamboo Panthenol Cream 100ml/Purito-0274-640x640.jpg`,
      `${YP}/Purito Mighty Bamboo Panthenol Cream 100ml/Purito-0275-640x640.jpg`,
    ],
    price: 27900,
    size: "100 ml",
    tipoProducto: "Crema",
    beneficio: "Hidratación profunda",
    tipoPiel: "Seca",
    concern: "Hidratación",
  },
  {
    id: 32,
    name: "Wonder Releaf Centella BB Cream",
    brand: "Purito",
    store: "YEPPO",
    category: "Hidratantes",
    description:
      "BB cream con Centella para cobertura ligera y natural. Unifica el tono, hidrata y calma la piel con SPF incluido.",
    images: [
      `${YP}/[Purito] Wonder Releaf Centella BB Cream/BB-Cream_color_pc-1536x853.jpg`,
      `${YP}/[Purito] Wonder Releaf Centella BB Cream/Purito-0283-1-700x700.jpg`,
      `${YP}/[Purito] Wonder Releaf Centella BB Cream/Purito-0283-1536x15236.jpg`,
    ],
    price: 15900,
    size: "30 ml",
  },
  {
    id: 33,
    name: "Wonder Releaf Centella Unscented Mini Kit",
    brand: "Purito",
    store: "YEPPO",
    category: "Sets & Kits",
    description:
      "Mini kit sin fragancia de la línea Centella. Ideal para pieles reactivas: limpiador, tónico y crema en formato de prueba.",
    images: [
      `${YP}/[Purito] Wonder Releaf Centella Unscented Mini Kit/Purito-0251-1536x1536.jpg`,
      `${YP}/[Purito] Wonder Releaf Centella Unscented Mini Kit/Purito-0252-1536x1536.jpg`,
      `${YP}/[Purito] Wonder Releaf Centella Unscented Mini Kit/Purito-0253-1536x1536.jpg`,
    ],
    price: 20900,
    beneficio: "Humectación profunda",
    tipoPiel: "Sensible, seca, normal",
    concern: "Calmante",
  },

  // ── ROUND LAB ────────────────────────────────────────────
  {
    id: 34,
    name: "1025 Dokdo Trial Kit",
    brand: "Round Lab",
    store: "YEPPO",
    category: "Sets & Kits",
    description:
      "Kit de prueba con la línea Dokdo: agua marina del océano profundo para piel sana, hidratada y sin brillos.",
    images: [
      `${YP}/[Round Lab] 1025 Dokdo Trial Kit/Round-Lab_-1025-Dokdo-Trial-Kit-1 (1).jpg`,
      `${YP}/[Round Lab] 1025 Dokdo Trial Kit/Round-Lab_-1025-Dokdo-Trial-Kit-2.jpg`,
      `${YP}/[Round Lab] 1025 Dokdo Trial Kit/Round-Lab_-1025-Dokdo-Trial-Kit-3.jpg`,
    ],
    price: 18900,
    beneficio: "Humectación profunda",
    tipoPiel: "Sensible",
    concern: "Hidratación",
  },
  {
    id: 35,
    name: "Birch Juice Trial Kit",
    brand: "Round Lab",
    store: "YEPPO",
    category: "Sets & Kits",
    description:
      "Set de la línea Birch Juice: jugo de abedul para hidratación profunda y efecto luminoso. Incluye tónico, sérum y crema.",
    images: [
      `${YP}/[Round Lab] Birch Juice Trial Kit/Round-Lab_-Birch-Juice-Trial-Kit-1-640x640.jpg`,
      `${YP}/[Round Lab] Birch Juice Trial Kit/Round-Lab_-Birch-Juice-Trial-Kit-3-640x640.jpg`,
      `${YP}/[Round Lab] Birch Juice Trial Kit/Round-Lab_-Birch-Juice-Trial-Kit-4.jpg`,
      `${YP}/[Round Lab] Birch Juice Trial Kit/Round-Lab_-Birch-Juice-Trial-Kit-5.jpg`,
    ],
    price: 18900,
    beneficio: "Hidratación glow",
    tipoPiel: "Seca",
    concern: "Hidratación",
  },
  {
    id: 36,
    name: "Mugwort Calming Mask",
    brand: "Round Lab",
    store: "YEPPO",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla de artemisa (mugwort) para calmar pieles reactivas. Rica en antioxidantes, reduce la rojez y reequilibra la piel sensible.",
    images: [
      `${YP}/[Round Lab] Mugwort Calming Mask/Round-Lab-Mugwort-Calming-Mask-1.jpg`,
      `${YP}/[Round Lab] Mugwort Calming Mask/Round-Lab-Mugwort-Calming-Mask-2.jpg`,
    ],
    price: 3000,
    size: "1 u",
    tipoProducto: "Máscara",
    beneficio: "Calmante rápido",
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 37,
    name: "Pine Calming Cica Trial Kit",
    brand: "Round Lab",
    store: "YEPPO",
    category: "Sets & Kits",
    description:
      "Kit con activos de pino y cica para pieles sensibles. Calma, repara y restablece el equilibrio cutáneo en un ritual completo.",
    images: [
      `${YP}/[Round Lab] Pine Calming Cica Trial Kit/Round-0571-1536x1536.jpg`,
      `${YP}/[Round Lab] Pine Calming Cica Trial Kit/Round-0572-1536x1536.jpg`,
      `${YP}/[Round Lab] Pine Calming Cica Trial Kit/Round-0573-1536x1536.jpg`,
      `${YP}/[Round Lab] Pine Calming Cica Trial Kit/Round-0574-640x640.jpg`,
      `${YP}/[Round Lab] Pine Calming Cica Trial Kit/Round-0575-640x640.jpg`,
    ],
    price: 20900,
    beneficio: "Calmante",
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 38,
    name: "Soybean Nourishing Mask",
    brand: "Round Lab",
    store: "YEPPO",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla nutritiva de soja para piel seca y deshidratada. Repone lípidos y deja la piel suave, flexible y con brillo saludable.",
    images: [
      `${YP}/[Round Lab] Soybean Nourishing Mask/Round-Lab-Soybean-Nourishing-Mask-1.jpg`,
      `${YP}/[Round Lab] Soybean Nourishing Mask/Round-Lab-Soybean-Nourishing-Mask-2.jpg`,
    ],
    price: 3000,
    size: "1 u",
    tipoProducto: "Máscara",
  },

  // ── SKIN1004 ─────────────────────────────────────────────
  {
    id: 39,
    name: "Centella Ampoule 100ml",
    brand: "SKIN1004",
    store: "BS",
    category: "Sueros",
    tag: "Bestseller",
    featured: true,
    description:
      "La ampolla de Centella más amada del K-beauty. Concentrado puro al 100% que calma, repara y fortalece la barrera cutánea.",
    images: [
      `${BS}/SKIN1004 Centella Ampoule 100 ML – Serum Piel Sensible/skin1004-ampoule-serum-centella-ampoule-38409088401654_1800x1800-1024x1024.webp`,
      `${BS}/SKIN1004 Centella Ampoule 100 ML – Serum Piel Sensible/skin1004-ampoule-serum-madagascar-centella-ampoule-36426919379190_900x900_800x_32cea7a8-d614-4592-ad29-c869d2faa04e.webp`,
      `${BS}/SKIN1004 Centella Ampoule 100 ML – Serum Piel Sensible/skin1004-skn-26066-2.webp`,
      `${BS}/SKIN1004 Centella Ampoule 100 ML – Serum Piel Sensible/skin1004-skn-26066.webp`,
    ],
    price: 26900,
    size: "100 ml",
    tipoProducto: "Serum",
    beneficio: "Repara piel",
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 40,
    name: "Centella Cream 75ml",
    brand: "SKIN1004",
    store: "BS",
    category: "Hidratantes",
    description:
      "Crema ligera con Centella al 52%. Hidratación duradera en textura gel-crema que absorbe al instante sin sensación pegajosa.",
    images: [
      `${BS}/SKIN1004 Centella Cream – Crema Facial 75ml/skin1004-cream-centella-cream-38409119269110_1800x1800-1024x1024.webp`,
      `${BS}/SKIN1004 Centella Cream – Crema Facial 75ml/skin1004-cream-centella-cream-38642822906102_1800x1800-1024x1024.webp`,
    ],
    price: 24900,
    size: "75 ml",
    tipoProducto: "Crema",
    beneficio: "Repara barrera, firmeza",
    tipoPiel: "Sensible, seca",
    concern: "Calmante",
  },
  {
    id: 41,
    name: "Centella Double Cleansing Duo",
    brand: "SKIN1004",
    store: "BS",
    category: "Sets & Kits",
    description:
      "Dúo de doble limpieza: aceite + espuma de Centella. Elimina hasta el maquillaje más resistente en dos pasos suaves.",
    images: [
      `${BS}/SKIN1004 Centella Double Cleansing Duo – Set doble Limpieza Facial/skin1004-cleanser-centella-ampoule-foam-38409123397878_1800x1800-1024x1024.webp`,
      `${BS}/SKIN1004 Centella Double Cleansing Duo – Set doble Limpieza Facial/skin1004-madagascar-centella-double-cleansing-power-duo-skin-care-skin1004-sri-lanka-orion-beauty-skin1004-offici.webp`,
      `${BS}/SKIN1004 Centella Double Cleansing Duo – Set doble Limpieza Facial/skin1004-skn-26112-4.webp`,
    ],
    price: 36900,
    beneficio: "Limpieza doble",
    tipoPiel: "Sensible, seca, normal",
    concern: "Limpieza",
  },
  {
    id: 42,
    name: "Centella Hyalu-Cica Sleeping Pack 100ml",
    brand: "SKIN1004",
    store: "BS",
    category: "Hidratantes",
    description:
      "Mascarilla de noche con Centella e ácido hialurónico. Actúa mientras duermes para despertar con piel rellena, luminosa y reparada.",
    images: [
      `${BS}/SKIN1004 Centella Hyalu-Cica Sleeping Pack 100ml/221121_Sleeping-Pack-1024x1024.jpg`,
      `${BS}/SKIN1004 Centella Hyalu-Cica Sleeping Pack 100ml/220804_Sleeping-Pack_2-683x1024.jpg`,
      `${BS}/SKIN1004 Centella Hyalu-Cica Sleeping Pack 100ml/220804_Sleeping-Pack_3-683x1024.jpg`,
    ],
    price: 23900,
    size: "100 ml",
    beneficio: "Hidratación profunda",
    tipoPiel: "Seca",
    concern: "Hidratación",
  },
  {
    id: 43,
    name: "Centella Travel Kit – Mini Tallas",
    brand: "SKIN1004",
    store: "BS",
    category: "Sets & Kits",
    description:
      "Set de viaje con los clásicos de Centella en mini talla. Mantén tu rutina K-beauty en cualquier destino.",
    images: [
      `${BS}/SKIN1004 Centella Travel Kit – Set de Viaje Mini tallas/220819_Travel-Kit_2-770x1024.jpg`,
      `${BS}/SKIN1004 Centella Travel Kit – Set de Viaje Mini tallas/200402_Travel-Kit_2-801x1024.jpg`,
    ],
    price: 36900,
    tipoPiel: "Sensible, seca, normal",
    concern: "Hidratación",
  },
  {
    id: 44,
    name: "Daily Essential Travel Kit – 4 pzs",
    brand: "SKIN1004",
    store: "BS",
    category: "Sets & Kits",
    description:
      "Kit de viaje completo con 4 esenciales diarios: limpiador, tónico, crema y protector solar. Todo en un pack práctico.",
    images: [
      `${BS}/SKIN1004 Daily Essential Travel Kit 4 piezas/DAILY0.webp`,
      `${BS}/SKIN1004 Daily Essential Travel Kit 4 piezas/DAILY2.webp`,
      `${BS}/SKIN1004 Daily Essential Travel Kit 4 piezas/DAILY3.webp`,
      `${BS}/SKIN1004 Daily Essential Travel Kit 4 piezas/DAILY4.webp`,
      `${BS}/SKIN1004 Daily Essential Travel Kit 4 piezas/DAILY6.webp`,
    ],
    price: 31900,
    tipoPiel: "Sensible, seca, normal",
    concern: "Manchas",
  },
  {
    id: 45,
    name: "Madagascar Centella Air-Fit Suncream Plus SPF50+ 50ml",
    brand: "SKIN1004",
    store: "BS",
    category: "Protección Solar",
    description:
      "Protector solar mineral con Centella SPF50+. Acabado invisible y ultraligero, sin residuo blanco, apto para pieles sensibles.",
    images: [
      `${BS}/SKIN1004 Madagascar Centella Air-Fit Suncream Plus SPF 50+ – Protector Solar Mineral – 50 ml/skin1004-sun-50ml-centella-air-fit-suncream-plus-spf50-pa-38642816647414_1800x1800.webp`,
    ],
    price: 23900,
    size: "50 ml",
    tipoProducto: "Protector Solar",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },
  {
    id: 46,
    name: "Madagascar Centella Cream 30ml – Mini Talla",
    brand: "SKIN1004",
    store: "BS",
    category: "Hidratantes",
    description:
      "Mini talla de la crema de Centella más amada del K-beauty. Hidratación intensa con textura ligera para llevar siempre contigo.",
    images: [
      `${BS}/SKIN1004 Madagascar Centella Cream 30 ml – Mini Talla/skin1004-cream-30ml-centella-cream-40739319513334_1000x1000-1.webp`,
    ],
    price: 7500,
    size: "30 ml",
    tipoProducto: "Crema",
    beneficio: "Repara barrera",
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 47,
    name: "Madagascar Centella Sheet Mask",
    brand: "SKIN1004",
    store: "BS",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla de tela individual con extracto de Centella. 20 minutos de intensa hidratación y calma para pieles irritadas.",
    images: [
      `${BS}/SKIN1004 Madagascar Centella Sheet Mask – Mascarilla Facial 1 pieza/2-1024x1024.webp`,
      `${BS}/SKIN1004 Madagascar Centella Sheet Mask – Mascarilla Facial 1 pieza/madascar-centella-watergel-sheet-ampoule-mask-by-skin1004-_mascarilla-hidratante_ee22fa70-dbe2-4037-a598-4e0372e.webp`,
    ],
    price: 3500,
    size: "1 u",
    tipoProducto: "Máscara",
  },
  {
    id: 48,
    name: "Madagascar Centella Toning Toner 210ml",
    brand: "SKIN1004",
    store: "BS",
    category: "Tónicos",
    description:
      "Tónico acuoso con Centella al 70%. Prepara la piel para absorber activos, aporta hidratación inicial y calma la irritación.",
    images: [
      `${BS}/SKIN1004 Madagascar Centella Toning Toner 210 ml – Tónico Piel Sensible/SKIN1004_-Madagascar-Centella-Toning-Toner_2048x_91fb13af-9683-4e22-8fbb-d77a1a8d19e4.webp`,
      `${BS}/SKIN1004 Madagascar Centella Toning Toner 210 ml – Tónico Piel Sensible/skin1004madagascartoningtoner-1024x951.webp`,
    ],
    price: 19900,
    size: "210 ml",
    tipoProducto: "Tónico",
    beneficio: "Hidratación ligera",
    tipoPiel: "Mixta",
    concern: "Hidratación",
  },
  {
    id: 49,
    name: "Poremizing Velvet Finish SPF50+",
    brand: "SKIN1004",
    store: "BS",
    category: "Protección Solar",
    description:
      "Fotoprotector con acabado aterciopelado que controla el brillo y minimiza la apariencia de los poros. SPF50+ sin sensación grasa.",
    images: [
      `${BS}/SKIN1004 Poremizing Velvet Finish – Fotoprotector SPF50+/dffghn.jpg`,
      `${BS}/SKIN1004 Poremizing Velvet Finish – Fotoprotector SPF50+/fbdh.jpg`,
      `${BS}/SKIN1004 Poremizing Velvet Finish – Fotoprotector SPF50+/gfdh.jpg`,
      `${BS}/SKIN1004 Poremizing Velvet Finish – Fotoprotector SPF50+/413pIA4snL._AC_SL1500_-3.jpg`,
    ],
    price: 23900,
    size: "50 ml",
    tipoProducto: "Protector Solar",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },
  {
    id: 50,
    name: "Retinol 0.2 + Retinal 0.05 Shot Ampoule 30ml",
    brand: "SKIN1004",
    store: "BS",
    category: "Sueros",
    description:
      "Ampolla con retinol y retinal para renovación celular acelerada. Reduce líneas finas y mejora la textura con activos de nueva generación.",
    images: [
      `${BS}/SKIN1004 Retinol 0.2  Retinal 0.05 – Shot Ampoule 30 ml/skin1004-30ml-retinol-0-2-boosting-shot-ampoule-1170007500_1440x.webp`,
      `${BS}/SKIN1004 Retinol 0.2  Retinal 0.05 – Shot Ampoule 30 ml/skin1004-30ml-retinol-0-2-boosting-shot-ampoule-1170007501_1440x.webp`,
      `${BS}/SKIN1004 Retinol 0.2  Retinal 0.05 – Shot Ampoule 30 ml/skin1004-30ml-retinol-0-2-boosting-shot-ampoule-1170007502_1440x.webp`,
      `${BS}/SKIN1004 Retinol 0.2  Retinal 0.05 – Shot Ampoule 30 ml/skin1004-30ml-retinol-0-2-boosting-shot-ampoule-1170007503_1440x.webp`,
      `${BS}/SKIN1004 Retinol 0.2  Retinal 0.05 – Shot Ampoule 30 ml/How_To_Use2_png_2a8cfff9-c6d4-47b4-a915-f5c5dcb95aa1.webp`,
      `${BS}/SKIN1004 Retinol 0.2  Retinal 0.05 – Shot Ampoule 30 ml/How_To_Use_png_74d4970e-a1aa-417c-a771-2ff7b70eb317.webp`,
    ],
    price: 24900,
    size: "30 ml",
    tipoProducto: "Shot",
    beneficio: "Antiage",
    tipoPiel: "Madura",
    concern: "Antiage",
  },
  {
    id: 51,
    name: "Set Quick Calming Duo",
    brand: "SKIN1004",
    store: "BS",
    category: "Sets & Kits",
    description:
      "Dúo calmante rápido: tónico + crema de Centella para pieles sensibles. Efecto SOS inmediato para los días de mayor estrés cutáneo.",
    images: [
      `${BS}/SKIN1004 SET QUICK CALMING DUO/SKIN1004-calming-duo.webp`,
      `${BS}/SKIN1004 SET QUICK CALMING DUO/skin1004-quick-calming-duo-1161163838_1440x-1024x1024.webp`,
      `${BS}/SKIN1004 SET QUICK CALMING DUO/skin1004-quick-calming-duo-1161163841_1440x-1024x1024.webp`,
      `${BS}/SKIN1004 SET QUICK CALMING DUO/Quick_Calming_Duo_Texture.webp`,
    ],
    price: 36900,
    beneficio: "Humectación profunda",
    tipoPiel: "Todo tipo",
    concern: "Calmante",
  },
  {
    id: 52,
    name: "Tea-Trica Cover Patch – 22 parches",
    brand: "SKIN1004",
    store: "BS",
    category: "Mascarillas & Pads",
    description:
      "22 parches discretos para el acné con extracto de té. Reducen rojez y tamaño del grano actuando también como cobertura natural.",
    images: [
      `${BS}/SKIN1004 Tea-Trica – Cover Patch – Parches para Acné 22 pzs/IMG_0270.webp`,
      `${BS}/SKIN1004 Tea-Trica – Cover Patch – Parches para Acné 22 pzs/patchOPEN_540x.webp`,
      `${BS}/SKIN1004 Tea-Trica – Cover Patch – Parches para Acné 22 pzs/patchVBLIZI_540x.webp`,
    ],
    price: 3500,
    size: "1 u",
    tipoProducto: "Máscara",
    beneficio: "Seca granos",
    tipoPiel: "Grasa",
    concern: "Acné",
  },
  {
    id: 53,
    name: "Tone Brightening Tone-Up SPF50+ 50ml",
    brand: "SKIN1004",
    store: "BS",
    category: "Protección Solar",
    description:
      "Fotoprotector y despigmentante en uno. Unifica el tono, aporta luminosidad y protege del sol con SPF50+ en un solo paso.",
    images: [
      `${BS}/SKIN1004 Tone Brightening Tone-up – Protector Solar SPF50 + – Despigmentante – tubo de50ml/skin1004-madagascar-centella-tone-brightening-tone-up-sunscreen-37793801568502_1000x1000.webp`,
      `${BS}/SKIN1004 Tone Brightening Tone-up – Protector Solar SPF50 + – Despigmentante – tubo de50ml/skin1004-madagascar-centella-tone-brightening-tone-up-sunscreen-37793801601270_1000x1000.webp`,
      `${BS}/SKIN1004 Tone Brightening Tone-up – Protector Solar SPF50 + – Despigmentante – tubo de50ml/skin1004-sun-tone-brightening-tone-up-sunscreen-38409247490294_1800x1800-1024x1024.webp`,
    ],
    price: 23900,
    size: "50 ml",
    tipoProducto: "Protector Solar",
    beneficio: "Protección y manchas",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },
  {
    id: 54,
    name: "Centella Hylu-Cica Jelly-Fit Ampoule Pads – 60 pzs",
    brand: "SKIN1004",
    store: "BS",
    category: "Mascarillas & Pads",
    description:
      "60 pads hidratantes en formato jelly con Centella e ácido hialurónico. Hidratación express que agiliza tu rutina sin sacrificar resultados.",
    images: [
      `${BS}/SKIN1004 – Centella Hylu-Cica Jelly-Fit Ampoule – Pads Hidratantes – 60 pzs/XXL_p0221067833.webp`,
      `${BS}/SKIN1004 – Centella Hylu-Cica Jelly-Fit Ampoule – Pads Hidratantes – 60 pzs/hyalu.png`,
      `${BS}/SKIN1004 – Centella Hylu-Cica Jelly-Fit Ampoule – Pads Hidratantes – 60 pzs/hyalu2.png`,
      `${BS}/SKIN1004 – Centella Hylu-Cica Jelly-Fit Ampoule – Pads Hidratantes – 60 pzs/hyalu3.png`,
      `${BS}/SKIN1004 – Centella Hylu-Cica Jelly-Fit Ampoule – Pads Hidratantes – 60 pzs/hyalu4.png`,
    ],
    price: 26900,
    size: "60 u",
    beneficio: "Hidratante",
    tipoPiel: "Todo tipo",
    concern: "Calmante",
  },
  {
    id: 55,
    name: "Madagascar Centella Ampoule",
    brand: "SKIN1004",
    store: "YEPPO",
    category: "Sueros",
    description:
      "Concentrado puro de Centella Asiatica para calmar, reparar y fortalecer la piel. Un clásico indispensable del skincare coreano.",
    images: [
      `${YP}/[Skin1004] Madagascar Centella Ampoule/MadagascarCentellaLightCleansingOil.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Ampoule/Skin1004CentellaAmpoule02.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Ampoule/Skin1004CentellaAmpoule03-640x640.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Ampoule/Skin1004CentellaAmpoule05.jpg`,
    ],
    price: 14900,
    size: "30 ml",
    tipoProducto: "Serum",
    beneficio: "Repara piel",
    tipoPiel: "Sensible",
    concern: "Calmante",
  },
  {
    id: 56,
    name: "Madagascar Centella Ampoule Foam",
    brand: "SKIN1004",
    store: "YEPPO",
    category: "Limpiadores",
    description:
      "Espuma limpiadora con extracto de Centella Ampoule. Limpieza suave y calmante que respeta la barrera cutánea en pieles sensibles.",
    images: [
      `${YP}/[Skin1004] Madagascar Centella Ampoule Foam/MadagascarCentellaAmpouleFoam.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Ampoule Foam/Madagascar_Centella_Ampoule_Foam_02-640x640.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Ampoule Foam/Madagascar_Centella_Ampoule_Foam_03.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Ampoule Foam/Madagascar_Centella_Ampoule_Foam_04.jpg`,
    ],
    price: 16900,
    size: "125 ml",
    tipoProducto: "Jabón",
  },
  {
    id: 57,
    name: "Madagascar Centella Light Cleansing Oil",
    brand: "SKIN1004",
    store: "YEPPO",
    category: "Limpiadores",
    description:
      "Aceite limpiador ligero con Centella. Fórmula no comedogénica que disuelve maquillaje y SPF sin dejar sensación grasa.",
    images: [
      `${YP}/[Skin1004] Madagascar Centella Light Cleansing Oil/MadagascarCentellaLightCleansingOil.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Light Cleansing Oil/Madagascar_Centella_Light_Cleansing_Oil_02.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Light Cleansing Oil/Madagascar_Centella_Light_Cleansing_Oil_03.jpg`,
      `${YP}/[Skin1004] Madagascar Centella Light Cleansing Oil/Madagascar_Centella_Light_Cleansing_Oil_05-640x640.jpg`,
    ],
    price: 21900,
    size: "200 ml",
    tipoProducto: "Limpiador oil",
  },
  {
    id: 58,
    name: "Sun Stick Centella",
    brand: "SKIN1004",
    store: "YEPPO",
    category: "Protección Solar",
    description:
      "Protector solar en stick con Centella. Cómodo, portátil y sin residuo blanco. Perfecto para retoques durante el día.",
    images: [
      `${YP}/Skin 1004 Sun Stick Centella/PlantillaFotosWeb_1_1_85211dc7-5494-47e7-be89-010eb13ab9d7.jpg`,
      `${YP}/Skin 1004 Sun Stick Centella/PlantillaFotosWeb_1_2_d6434c4a-6f38-43b9-a093-2d04f4e42c11.jpg`,
      `${YP}/Skin 1004 Sun Stick Centella/PlantillaFotosWeb_1_3_4577974d-92ca-4c70-a241-3d5794ff4cb3.jpg`,
      `${YP}/Skin 1004 Sun Stick Centella/PlantillaFotosWeb_1_5_aae4b0d3-7829-4e76-908d-6f6f72ad9598-640x640.jpg`,
    ],
    price: 19900,
    size: "20 g",
    tipoProducto: "Protector Solar",
    beneficio: "Protección portátil",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },
  {
    id: 59,
    name: "Madagascar Centella Hyalu-Cica Water-Fit Sun Serum",
    brand: "SKIN1004",
    store: "YEPPO",
    category: "Protección Solar",
    description:
      "Sérum solar acuoso con Centella e ácido hialurónico. Protección y tratamiento en uno: hidrata, calma y protege con acabado invisible.",
    images: [
      `${YP}/Skin1004 Protector Solar Madagascar Centella Hyalu-Cica Water-Fit Sun Serum/PW_SKI000901_SKIN1004-Madagascar-Centella-Hyalu-Cica-Water-Fit-Sun-Serum-50ml_001-1.jpg`,
      `${YP}/Skin1004 Protector Solar Madagascar Centella Hyalu-Cica Water-Fit Sun Serum/SKU_SKIN1004-Madagascar-Centella-Hyalu-Cica-Water-Fit-Sun-Serum-50ml_003.jpg`,
      `${YP}/Skin1004 Protector Solar Madagascar Centella Hyalu-Cica Water-Fit Sun Serum/SKU_SKIN1004-Madagascar-Centella-Hyalu-Cica-Water-Fit-Sun-Serum-50ml_004.jpg`,
    ],
    price: 19900,
    size: "50 ml",
    tipoProducto: "Protector Solar",
    beneficio: "Protección solar",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },

  // ── SOME BY MI ───────────────────────────────────────────
  {
    id: 60,
    name: "AHA BHA PHA 30 Days Miracle AC SOS Kit",
    brand: "Some By Mi",
    store: "YEPPO",
    category: "Sets & Kits",
    tag: "Bestseller",
    description:
      "El kit anti-acné de 30 días con AHA, BHA y PHA. Transforma la piel con exfoliantes y activos anti-imperfecciones de alta eficacia.",
    images: [
      `${YP}/[Somebymi] Aha-Bha-Pha 30 Days Miracle AC SOS Kit/SOMEBYMI_-Aha-Bha-Pha-30-Days-Miracle-AC-SOS-Kit-1.jpg`,
      `${YP}/[Somebymi] Aha-Bha-Pha 30 Days Miracle AC SOS Kit/SOMEBYMI_-Aha-Bha-Pha-30-Days-Miracle-AC-SOS-Kit-4-640x640.jpg`,
      `${YP}/[Somebymi] Aha-Bha-Pha 30 Days Miracle AC SOS Kit/SOMEBYMI_-Aha-Bha-Pha-30-Days-Miracle-AC-SOS-Kit-5.jpg`,
      `${YP}/[Somebymi] Aha-Bha-Pha 30 Days Miracle AC SOS Kit/SOMEBYMI_-Aha-Bha-Pha-30-Days-Miracle-AC-SOS-Kit-7-640x640.jpg`,
    ],
    price: 28900,
    beneficio: "Control acné",
    tipoPiel: "Grasa",
    concern: "Acné",
  },

  // ── TOCOBO ───────────────────────────────────────────────
  {
    id: 61,
    name: "Bio Watery Sun Cream SPF50+ PA++++",
    brand: "Tocobo",
    store: "YEPPO",
    category: "Protección Solar",
    description:
      "Crema solar acuosa ultraligera con activos botánicos. Textura gel que se funde con la piel sin residuo blanco, ideal para uso diario.",
    images: [
      `${YP}/[Tocobo] Bio Watery Sun Cream SPF50+ PA++++/Tocobo_-BIO-WATERY-SUN-CREAM-SPF50__PA-640x640.jpg`,
      `${YP}/[Tocobo] Bio Watery Sun Cream SPF50+ PA++++/Tocobo_-BIO-WATERY-SUN-CREAM-SPF50__PA__02.jpg`,
      `${YP}/[Tocobo] Bio Watery Sun Cream SPF50+ PA++++/Tocobo_-BIO-WATERY-SUN-CREAM-SPF50__PA__06.jpg`,
      `${YP}/[Tocobo] Bio Watery Sun Cream SPF50+ PA++++/Tocobo_-BIO-WATERY-SUN-CREAM-SPF50__PA__07.jpg`,
    ],
    price: 23900,
    size: "50 ml",
    tipoProducto: "Protector Solar",
    beneficio: "Protección solar",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },
  {
    id: 62,
    name: "Cotton Soft Sun Stick SPF50+ PA++++",
    brand: "Tocobo",
    store: "YEPPO",
    category: "Protección Solar",
    description:
      "Stick solar de textura suave como algodón. SPF50+ PA++++ en formato portátil para retoques rápidos y prácticos durante el día.",
    images: [
      `${YP}/[Tocobo] Cotton Soft Sun Stick SPF50+  PA++++/Tocobo_-COTTON-SOFT-SUN-STICK-SPF50_-PA.jpg`,
      `${YP}/[Tocobo] Cotton Soft Sun Stick SPF50+  PA++++/Tocobo_-COTTON-SOFT-SUN-STICK-SPF50_-PA_-03.jpg`,
      `${YP}/[Tocobo] Cotton Soft Sun Stick SPF50+  PA++++/Tocobo_-COTTON-SOFT-SUN-STICK-SPF50_-PA_-04-640x640.jpg`,
      `${YP}/[Tocobo] Cotton Soft Sun Stick SPF50+  PA++++/Tocobo_-COTTON-SOFT-SUN-STICK-SPF50_-PA_-05.jpg`,
    ],
    price: 24900,
    tipoProducto: "Protector Solar",
    beneficio: "Protección portátil",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },
  {
    id: 63,
    name: "Vita Tone Up Sun Cream SPF50+ PA++++ 50ml",
    brand: "Tocobo",
    store: "YEPPO",
    category: "Protección Solar",
    featured: true,
    description:
      "Crema solar con tono unificador y vitaminas antioxidantes. SPF50+ PA++++ con efecto glow natural que aporta luminosidad al instante.",
    images: [
      `${YP}/[Tocobo] Vita Tone Up Sun Cream SPF50+ PA++++ 50ml/Tocobo_-VITA-TONE-UP-SUN-CREAM-SPF50_-PA_-02.jpg`,
      `${YP}/[Tocobo] Vita Tone Up Sun Cream SPF50+ PA++++ 50ml/Tocobo_-VITA-TONE-UP-SUN-CREAM-SPF50_-PA_-04.jpg`,
      `${YP}/[Tocobo] Vita Tone Up Sun Cream SPF50+ PA++++ 50ml/Tocobo_-VITA-TONE-UP-SUN-CREAM-SPF50_-PA_-06_630x630.webp`,
      `${YP}/[Tocobo] Vita Tone Up Sun Cream SPF50+ PA++++ 50ml/Tocobo_-VITA-TONE-UP-SUN-CREAM-SPF50_-PA_-08.jpg`,
      `${YP}/[Tocobo] Vita Tone Up Sun Cream SPF50+ PA++++ 50ml/Tocobo_-VITA-TONE-UP-SUN-CREAM-SPF50_-PA_12-640x640.jpg`,
    ],
    price: 25900,
    size: "50 ml",
    tipoProducto: "Protector Solar",
    beneficio: "Protección solar",
    tipoPiel: "Todo tipo",
    concern: "Protector solar",
  },

  // ── VT COSMETICS ─────────────────────────────────────────
  {
    id: 64,
    name: "Reedle Shot 50 – 30ml",
    brand: "VT Cosmetics",
    store: "YEPPO",
    category: "Sueros",
    description:
      "Ampolla con agujas solubles al 50%. La entrada perfecta al mundo Reedle Shot: rellena líneas finas y mejora la textura sin agujas reales.",
    images: [
      `${YP}/[VT] REEDLE SHOT 50 30 ml/VT-022-1-700x700.jpg`,
      `${YP}/[VT] REEDLE SHOT 50 30 ml/VT-022-2-1536x1536.jpg`,
      `${YP}/[VT] REEDLE SHOT 50 30 ml/VT-022-3-1536x1536.jpg`,
      `${YP}/[VT] REEDLE SHOT 50 30 ml/VT-022-4-640x640.jpg`,
    ],
    price: 20000,
    size: "30 ml",
    tipoProducto: "Antiage",
    beneficio: "Rejuvenecimiento",
    tipoPiel: "Madura",
    concern: "Antiage",
  },
  {
    id: 65,
    name: "Reedle Shot 100",
    brand: "VT Cosmetics",
    store: "YEPPO",
    category: "Sueros",
    description:
      "Nivel intensivo de agujas solubles al 100%. Efecto lifting visible, plump y reducción de arrugas para quienes buscan resultados reales.",
    images: [
      `${YP}/[VT] Reedle Shot 100/VT-001-1-700x700.jpg`,
      `${YP}/[VT] Reedle Shot 100/VT-001-2-640x640.jpg`,
      `${YP}/[VT] Reedle Shot 100/VT-001-3-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot 100/VT-001-4-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot 100/VT-001-5-640x640.jpg`,
    ],
    price: 30900,
    size: "50 ml",
    tipoProducto: "Antiage",
    beneficio: "Rejuvenecimiento",
    tipoPiel: "Madura",
    concern: "Antiage",
  },
  {
    id: 66,
    name: "Reedle Shot 300 – 30ml",
    brand: "VT Cosmetics",
    store: "YEPPO",
    category: "Sueros",
    tag: "Premium",
    description:
      "La fórmula más concentrada de Reedle Shot. Máxima potencia para transformar la textura, tono y relleno cutáneo en un ciclo completo.",
    images: [
      `${YP}/[VT] Reedle Shot 300 30 ml/VT-002-1-700x700.jpg`,
      `${YP}/[VT] Reedle Shot 300 30 ml/VT-002-2-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot 300 30 ml/VT-002-3-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot 300 30 ml/VT-002-4-640x640.jpg`,
    ],
    price: 27000,
    size: "30 ml",
    tipoProducto: "Antiage",
    beneficio: "Antiage intensivo",
    tipoPiel: "Madura",
    concern: "Antiage",
  },
  {
    id: 67,
    name: "Reedle Shot Ex Cica Modeling Pack",
    brand: "VT Cosmetics",
    store: "YEPPO",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla modeling con Reedle Shot y cica. Se aplica como pasta y solidifica para un efecto tensor y calmante a nivel profesional.",
    images: [
      `${YP}/[VT] Reedle Shot Ex Cica Modeling Pack/VT-0291-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Cica Modeling Pack/VT-0292-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Cica Modeling Pack/VT-0293-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Cica Modeling Pack/VT-0294-640x640.jpg`,
    ],
    price: 7000,
    tipoProducto: "Mascarilla",
    concern: "Calmante",
  },
  {
    id: 68,
    name: "Reedle Shot Ex Collagen Modeling Pack",
    brand: "VT Cosmetics",
    store: "YEPPO",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla modeling con Reedle Shot y colágeno. Efecto tensor y antienvejecimiento en 20 minutos, piel firme y visiblemente rellena.",
    images: [
      `${YP}/[VT] Reedle Shot Ex Collagen Modeling Pack/VT-0281-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Collagen Modeling Pack/VT-0282-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Collagen Modeling Pack/VT-0283-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Collagen Modeling Pack/VT-0284-640x640.jpg`,
    ],
    price: 7000,
    tipoProducto: "Mascarilla",
    concern: "Antiage",
  },
  {
    id: 69,
    name: "Reedle Shot Ex Vitamin Modeling Pack",
    brand: "VT Cosmetics",
    store: "YEPPO",
    category: "Mascarillas & Pads",
    description:
      "Mascarilla modeling con Reedle Shot y vitaminas. Ilumina, uniforma y nutre con un ritual K-beauty a nivel profesional en casa.",
    images: [
      `${YP}/[VT] Reedle Shot Ex Vitamin Modeling Pack/VT-0301-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Vitamin Modeling Pack/VT-0302-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Vitamin Modeling Pack/VT-0303-1536x1536.jpg`,
      `${YP}/[VT] Reedle Shot Ex Vitamin Modeling Pack/VT-0304-640x640.jpg`,
    ],
    price: 7000,
    tipoProducto: "Mascarilla",
    concern: "Antiage",
  },
];

export const categories: ProductCategory[] = [
  "Todos",
  "Limpiadores",
  "Tónicos",
  "Sueros",
  "Hidratantes",
  "Mascarillas & Pads",
  "Protección Solar",
  "Sets & Kits",
  "Cabello",
];

export const featuredProducts = products.filter((p) => p.featured);
